export const USER = {
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAILED: "CREATE_ORDER_FAILED",
  CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST",
  UPDATE_ORDER_FAILED: "UPDATE_ORDER_FAILED",
  UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",
  UPDATE_ORDER_REQUEST: "UPDATE_ORDER_REQUEST",
  FETCH_ORDER_SUCCESS: "FETCH_ORDER_SUCCESS",
  FETCH_ORDER_REQUEST: "FETCH_ORDER_REQUEST",
  FETCH_ORDER_FAILED: "FETCH_ORDER_FAILED",
  FETCH_ALL_ORDERS_REQUEST: "FETCH_ALL_ORDERS_REQUEST",
  FETCH_ALL_ORDERS_SUCCESS: "FETCH_ALL_ORDERS_SUCCESS",
  FETCH_ALL_ORDERS_FAILED: "FETCH_ALL_ORDERS_FAILED",
};
